apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-app-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: task-app-role
subjects:
- kind: ServiceAccount
  name: task-app
